version: "3.8"

services:
  fp-be:
    build: ./
    container_name: fp-be
    ports:
      - '3000:3000'
    command:
      - "nodemon"
      - "--inspect"
      - "app.js"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env